# fly.toml app configuration file generated for notesapp-lautaro-ensolvers on 2023-08-05T16:35:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "notesapp-lautaro-ensolvers"
primary_region = "gig"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
